### ISSUE TITLE
Avoid dependency on scheduler jobs assemblies

### ISSUE THREAD

**Issue by alexminza** [guryanovev/CrystalQuartz#16]
**Url:** /CrystalQuartzPanel.axd?page=job&job=_[JOB_REDACTED]_&group=DEFAULT

> Could not load file or assembly '_[ASSEMBLY_REDACTED]_' or one of its dependencies. The system cannot find the file specified.

![screen shot 2015-02-19 at 11 17 28](https://cloud.githubusercontent.com/assets/149919/6264092/f3b3b9b4-b828-11e4-8802-c0657614773c.png)

We run CrystalQuartz as a separate lightweight console that connects to the Quartz.net scheduler via remoting. When trying to access the job details page - the request fails since there are no binaries deployed with the console project - it is completely separated from the project.

**Comment by bruuteuzius** [comment]
I'm having the same issue... Do you have 2.3 installed? I'm thinking about updating the nuget package to the latest/gratest.
