### ISSUE TITLE
Allow editing of triggers

### ISSUE THREAD

**Issue by kwaclaw** [guryanovev/CrystalQuartz#18]
It would be really useful to have the ability to change frequencies and times for particular jobs.
In our environment the jobs don't change often, but the scheduled times do need to be changed on a regular basis.

**Comment by guryanovev** [comment]
There is now an option to add a trigger to an existing job

![add_trigger_1](https://cloud.githubusercontent.com/assets/2764795/25313832/b4413e30-283f-11e7-8307-76e092445b1b.png)

![add_trigger_2](https://cloud.githubusercontent.com/assets/2764795/25313834/b7faf002-283f-11e7-8103-31ea0634b911.png)
