### ISSUE TITLE
 Whether CrystalQuartz.Remote is able to support self-hosting

### ISSUE THREAD

**Issue by jello-chen** [guryanovev/CrystalQuartz#24]

**Comment by guryanovev** [comment]
Sorry for delay, currently CrystalQuartz.Remote is not able to be ran as a self-hosted service. But i agree it should be. It is probably the next big feature to implement.

**Comment by jello-chen** [comment]
Thanks for your answer

**Comment by guryanovev** [comment]
Self-hosted apps support is working since v4.0
Please see https://github.com/guryanovev/CrystalQuartz#option-1-owin for details.
