### ISSUE TITLE
Error reading resource 'CrystalQuartz.Web.Content.Scripts.application.js'

### ISSUE THREAD

**Issue by huoxudong125** [guryanovev/CrystalQuartz#25]
Severity    Code    Description Project File    Line    Suppression State
Error       Error reading resource`'CrystalQuartz.Web.Content.Scripts.application.js'`-- 'Could not find file 'D:\TestProjects\CrystalQuartz\src\CrystalQuartz.Web\Content\Scripts`application.js`'.'    CrystalQuartz.Web   D:\TestProjects\CrystalQuartz\src\CrystalQuartz.Web\CSC

**Comment by guryanovev** [comment]
application.js was an autogenerated file in old solution. Closing it now as it's not relevant any more.
