### ISSUE TITLE
once you have shutdown a scheduler, it cannot be restarted

### ISSUE THREAD

**Issue by shepherds126** [guryanovev/CrystalQuartz#31]
once you have shutdown a scheduler, it cannot be restarted,say: The Scheduler cannot be restarted after Shutdown() has been called.
![image](https://cloud.githubusercontent.com/assets/12708782/23778172/ac1a6202-0573-11e7-8e7f-7d2643dc3913.png)

**Comment by guryanovev** [comment]
This is by-design behaviour of Quartz.NET. Once the scheduler is shutdown it is not operational any more. Maybe it makes sense to add Pause and Resume buttons for the scheduler to emulate stop/restart functions.

**Comment by guryanovev** [comment]
Please use "Standby" instead of "Shutdown"

![image](https://user-images.githubusercontent.com/2764795/44773571-94c2ff80-ab79-11e8-8046-11fb7aca716a.png)
