### ISSUE TITLE
Add support for dotnet core

### ISSUE THREAD

**Issue by andymac4182** [guryanovev/CrystalQuartz#34]
It would be great if we could include this in our dotnet core applications. Is this something you would be interested in?

https://icanhasdot.net/result?github=guryanovev~2FCrystalQuartz

**Comment by guryanovev** [comment]
Yes, that is a good point, support for dotnet core should be added. But for now, I am not sure if Quartz.NET v2 inself supports it...

**Comment by andymac4182** [comment]
I can do the migration to the new csproj format. Once that is done it helps make the migration to core a lot simpler.

**Comment by guryanovev** [comment]
@andymac4182 It would be great, but I conserned about the code itself, for example, using `System.Web.Serialization` that is not available on dotnet core. Maybe I need to investigate it further, but it looks like the migration would not be so simple especially in terms of supporting both core and "classic" .NET at the same time.

**Comment by andymac4182** [comment]
Might need to split into 2 packages one for core and one for ASP.NET 4.x. Hopefully a lot of the logic could be in the main lib with them just being shims.

**Comment by moumenmosa** [comment]
I used it to connect on quartz in .net core but actually i faced issue while i try to connect using proxy it gave "Error communicating with remote scheduler." 
the configration it is as below

<quartz>
   

    <add key="quartz.scheduler.exporter.type" value="Quartz.Simpl.RemotingSchedulerExporter, Quartz" />
    <add key="quartz.scheduler.exporter.port" value="555" />
    <add key="quartz.scheduler.exporter.bindName" value="QuartzScheduler" />
    <add key="quartz.scheduler.exporter.channelType" value="tcp" />
    <add key="quartz.scheduler.exporter.channelName" value="httpQuartz" />
  
    <add key="quartz.scheduler.instanceName" value="RemoteServerSchedulerClient" />
    <add key="quartz.threadPool.type" value="Quartz.Simpl.SimpleThreadPool, Quartz" />
    <add key="quartz.threadPool.threadCount" value="5" />
    <add key="quartz.threadPool.threadPriority" value="Normal" />

    <add key="quartz.scheduler.proxy" value="true" />
    <add key="quartz.scheduler.proxy.address" value="tcp://127.0.0.1:555/QuartzScheduler" />
    
    

    <add key="quartz.jobStore.type" value="Quartz.Impl.AdoJobStore.JobStoreTX, Quartz"/>
      <add key="quartz.jobStore.dataSource" value="myDS"/>
      <add key="quartz.jobStore.driverDelegateType" value="Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz"/>
      <add key="quartz.jobStore.lockHandler.type" value="Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore, Quartz"/>
      <add key="quartz.jobStore.tablePrefix" value="QRTZ_"/>
      <add key="quartz.jobStore.clustered" value="false"/>
      <add key="quartz.dataSource.myDS.connectionString" value="Server=.;Database=QuartzDB;Persist Security Info=True;User ID=sa;Password=123;"/>
      <add key="quartz.dataSource.myDS.provider" value="SqlServer"/>
      <add key="quartz.jobStore.useProperties" value="true"/>
      <add key="quartz.serializer.type" value="json"/> 
  </quartz>

i think still it is not supported for .net core  :(

**Comment by djl394922860** [comment]
i hope so + 1

**Comment by guryanovev** [comment]
Core is supported now but please note that **there are known Quartz.NET issues with remote scheduler on .NET Core**
