### ISSUE TITLE
how to add  multiple  SchedulerHost in webconfig

### ISSUE THREAD

**Issue by WithLin** [guryanovev/CrystalQuartz#36]
```
 <add property="Type" value="CrystalQuartz.Core.SchedulerProviders.RemoteSchedulerProvider, CrystalQuartz.Core" />
<add property="SchedulerHost" value="tcp://localhost:555/TradePlatformInterfaceScheduler" />
 <add property="SchedulerHost" value="tcp://localhost2:555/TradePlatformInterfaceScheduler" />
```
 The WebUI only  see localhost:555/TradePlatformInterfaceScheduler ,but can not see
  localhost2:555/TradePlatformInterfaceScheduler. so how i do set the property?

**Comment by guryanovev** [comment]
The panel currently works for one scheduler only.

**Comment by WithLin0510** [comment]
oh,thank you ! i want to update the UI，which was failed to Update.  Would you wirte some tutorial? i was seeing code ,i am suggest you that Rosalia   instead of gulp.

**Comment by guryanovev** [comment]
Yes, Rosalia is a build tool, you need to run in to generate client side assets. Just run the Build.bat file from repository root.
