### ISSUE TITLE
CrystalQuartz.Owin does not depends to Microsoft.Owin.Host.SystemWeb

### ISSUE THREAD

**Issue by soroshsabz** [guryanovev/CrystalQuartz#37]
ITNOA

Hi,

I think, it is good idea to depends `CrystalQuartz.Owin` depends to `Microsoft.Owin.Host.SystemWeb`, because when I install `CrystalQuartz.Owin` package, `Microsoft.Owin.Host.SystemWeb` package does not install and Startup does not call, so your instruction does not work.

thx

**Comment by guryanovev** [comment]
Thank you for mentioning that

`Microsoft.Owin.Host.SystemWeb` is something specific to host environment so CrystalQuartz does not directly depend on it. In case of self-hosted owin app you probably can go without this dependency. I also believe all "modern" asp.net projects already have OWIN environment completely pre-installed and no direct installation of `Microsoft.Owin.Host.SystemWeb` is needed. Anyway, it is something that should be mentioned in CrystalQuartz getting started instructions.
