### ISSUE TITLE
Upgrade Quartz to 2.5.0

### ISSUE THREAD

**Issue by soroshsabz** [guryanovev/CrystalQuartz#38]
ITNOA

Hi , I think it is good idea to upgrade quartz to 2.5.0

**Comment by Godaday** [comment]
1.replace packages.config   Common.Logging 、Common.Logging.Core、Quartz  nodes
2. copy Common.Logging 3.3.1、Common.Logging.Core 3.3.1 、Quartz 2.5.0 DLL    to the directory（CrystalQuartz-master\examples\packages）;
3. netget  Uninstall CrystalQuartz.Owin  but  don't  remove   Common.Logging 、Common.Logging.Core、Quartz 
4. re-install   CrystalQuartz.Owin   complete！

**Comment by fzhenmei** [comment]
I just re-install CrystalQuartz.Owin 4.2.1 then can work with Quartz 2.5.0, but I don't know why...
