### ISSUE TITLE
CrystalQuartz-timeline missing files

### ISSUE THREAD

**Issue by zaryk** [guryanovev/CrystalQuartz#39]
Files are missing from the CrystalQuartz-timeline download, resulting in errors during build.   Doesn't look like the dist folder was included, which based on your .gitignore, this may be intended:

CrystalQuartz.Application/Content/application.css
CrystalQuartz.Application/Content/application.js
CrystalQuartz.Application/Content/index.html
CrystalQuartz.Application/Content/loading.gif

Is there something I can do to fix this, or do I need to wait for you to add them?

**Comment by guryanovev** [comment]
Please try run build procedure, it should generate the files. To do so you can run Debug->Start New Instance on CrystalQuartz.Build project or run Webpack manually with npm command:

    npm run build-debug

Working directory should be src/CrystalQuartz.Application.Client

**Comment by zaryk** [comment]
Cool, thanks, it worked!
