### ISSUE TITLE
Quartz.NET 3.0 & async/await support

### ISSUE THREAD

**Issue by CelsoSantos** [guryanovev/CrystalQuartz#41]
Hello,

I'd like to use CrystalQuartz within a project that relies on async/await functionality, however, it has come to my attention that Quartz.NET will only support this functionality starting on version 3.0.

Currently, there is already a beta available (https://github.com/quartznet/quartznet/releases/tag/v3.0.0-beta1) and even though it's not a final version I'd like to see a alpha/beta version of CrystalQuartz support for this.

Has the CrystalQuartz team started to develop something that could support this version of Quartz? In any case (yes or no) are there any plan currently to introduce this support and when that could be available even as a first draft?

I could be able to lend a hand at it (maybe a PR) but the truth is that I don't know the CrystalQuartz architecture nor how long it would take me to be able to do such PR.

This UI might be a make or break feature for the current project otherwise we would have to rely on some sort of console application instead of the UI.

Best Regards
Celso Santos

PS: Oh, also, merry Christmas :)

**Comment by msouphy** [comment]
+1

Quartz 3 has been officially released. It would be good if CrystalQuartz could be made compatible.

Thanks

**Comment by victorperez2911** [comment]
+1

**Comment by luigidallavalle** [comment]
Is there any plan to support version 3.0 or Quartz.NET?
If there is, is there any planned release date or roadmap?

thanks for the great project

**Comment by guryanovev** [comment]
We plan to implement 3.0 support in about a week.

**Comment by guryanovev** [comment]
First quartz3 version is out

    Install-Package CrystalQuartz.Owin -Version 6.1.0.8-beta -IncludePrerelease

As it's based on experimental v5 so still requires `-IncludePrerelease` flag. Next target is to actualize readme and merge v6 branch to master. Unfortunately .NET Core is not supported yet.

**Comment by guryanovev** [comment]
"Native" ASP.NET CORE is supported since v6.4.1
