### ISSUE TITLE
CrystalQuartz not working when running as windows service

### ISSUE THREAD

**Issue by Deepak690** [guryanovev/CrystalQuartz#48]
I have added crystal quartz in my quartz scheduler project to show the dashboard (check link). below code works fine when I am running the application as a console app. but it does not work when we deploy it as windows service on the same machine. it's not even throwing any exception nor any log in event logger.

IScheduler scheduler = SetupScheduler();
                Action<IAppBuilder> startup = app => 
                {
                    app.UseCrystalQuartz(scheduler);
                };

                Console.WriteLine("Starting self-hosted server...");
                using (WebApp.Start("http://localhost:9000/", startup))
                {
                    Console.WriteLine("Server is started");
                    Console.WriteLine();
                    Console.WriteLine("Check http://localhost:9000/quartz to see jobs information");
                    Console.WriteLine();

                    Console.WriteLine("Starting scheduler...");
                    scheduler.Start();

                    Console.WriteLine("Scheduler is started");
                    Console.WriteLine();
                    Console.WriteLine("Press [ENTER] to close");     
                    Console.ReadLine();     
                }

                Console.WriteLine("Shutting down...");
                scheduler.Shutdown(waitForJobsToComplete: true);
                Console.WriteLine("Scheduler has been stopped");

when we deploy the application as windows service I am getting below error while opening the link in the browser "This site can’t be reached". but its working fine when we run it as a console.

**Comment by guryanovev** [comment]
Is this code in Service Runner or just in Program.cs? It is possible that this code just does nor run in services mode.

**Comment by pink-sheep** [comment]
I have the same issue, the code sits in the service runner in the onStart override

**Comment by pink-sheep** [comment]
Right.. found the issue.. you need 
WebApp.Start("http://localhost:9000/", startup;
 scheduler.Start();

instead of using loop, otherwise Owin will stop hosting the website the moment you're service finishes starting up

**Comment by guryanovev** [comment]
@pink-sheep It's great you figured it out. A sample demonstrating usages with windows service might be needed to avoid such confusions.
