### ISSUE TITLE
Couldn't obtain triggers for job: The time zone ID '' was not found on the local computer

### ISSUE THREAD

**Issue by Gamain** [guryanovev/CrystalQuartz#51]
One or more errors occurred. (Couldn't obtain triggers for job: The time zone ID 'China Standard Time' was not found on the local computer.)
Couldn't obtain triggers for job: The time zone ID 'China Standard Time' was not found on the local computer.
The time zone ID 'China Standard Time' was not found on the local computer.
Could not find file '/usr/share/zoneinfo/China Standard Time'.

**Comment by Gamain** [comment]
One or more errors occurred. (Couldn't obtain triggers for job: The time zone ID 'China Standard Time' was not found on the local computer.)
Couldn't obtain triggers for job: The time zone ID 'China Standard Time' was not found on the local computer.
The time zone ID 'China Standard Time' was not found on the local computer.
Could not find file '/usr/share/zoneinfo/China Standard Time'.

**Comment by toftware** [comment]
Sounds more like a Quartz issue than CrystalQaurtz, i bet you have scheduled one thing from maybe Windows and are hosting on Linux. The timezone names are different between them.

**Comment by guryanovev** [comment]
This issue is more for Quartz.NET itself, not CrystalQuartz Panel. According to the [docs](https://www.quartz-scheduler.net/), there might be problems on linux related to timezones:

> KNOWN ISSUES
>
> * Issues with time zone ids between Windows and Linux, they use different ids for the same zone
> * No remoting support for .NET Core

You might need to use specific timezone id in trigger initialization code:

    // make sure id "GMT Standard Time" is known by the system
    var timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById("GMT Standard Time"); 

    TriggerBuilder
         .Create()
         .WithIdentity("...")
         .StartNow()
         .WithCronSchedule("...", csb => csb.InTimeZone(timeZoneInfo)).Build();

Closing for now.
