### ISSUE TITLE
About CrystalQuartz UI Authentication

### ISSUE THREAD

**Issue by djl394922860** [guryanovev/CrystalQuartz#56]
Is there any way to control access the UI page ? for example name/password or http basic authentication ? 
Thank you !

**Comment by djl394922860** [comment]
Is there anyone know that .... help

**Comment by guryanovev** [comment]
Please see this comment https://github.com/guryanovev/CrystalQuartz/issues/52#issuecomment-414628131

**Comment by djl394922860** [comment]
> Please see this comment [#52 (comment)](https://github.com/guryanovev/CrystalQuartz/issues/52#issuecomment-414628131)

thank you
