### ISSUE TITLE
ASP MVC or Core, how to create a new job

### ISSUE THREAD

**Issue by papyr** [guryanovev/CrystalQuartz#62]
Hello, I can see the dashboard monitor, but how can we create a new job of a task?

For e.g. I registered a list of runnable tasks in a static class and and want to be able to create a schedule around it

**Comment by mikhail-vazhenin** [comment]
Hello!

If I understand correctly, you need simply add new job with second parameter `true` (register job without trigger, but you can add trigger on UI). 
```c#
...
 c.Resolve<IScheduler>().AddJob(job, true, true));
...
```

**Comment by guryanovev** [comment]
@mikhail-vazhenin, right, adding jobs from UI is not supported yet as it is a really rare case. All the jobs are usually created at startup time. But that feature will probably be implemented in one of future releases.

**Comment by papyr** [comment]
hello @mikhail-vazhenin @guryanovev thanks for the response. our use case is based on our users, who creates jobs for vendors, and we are using your UI 👍

**Comment by papyr** [comment]
Hello, any chance we can get this feature to add jobs from the UI.

Also, which version in the samples runs the ASP MVC?
