### ISSUE TITLE
Does CrystalQuartz support .net 4.6.1 ? 

### ISSUE THREAD

**Issue by chaoscn** [guryanovev/CrystalQuartz#70]
Hi, 

Does CrystalQuartz support .net 4.6.1 ? 
I saw the examples are all in 4.5.2 and when I switch the program type to 4.6.1, it did not work.

Regards,
Chenhao Gao

**Comment by guryanovev** [comment]
Yes, sure, CrystalQuartz supports any newer .NET versions.
Examples could break after the switch because of some issues with other libraries. On new project it should be fine. Closing the issue for now, fill free to open in case of any updates.
