### ISSUE TITLE
Upgrade to .net core 3.0

### ISSUE THREAD

**Issue by heyixiaoran** [guryanovev/CrystalQuartz#84]
It seems doesn't support .net core 3.0.
After I update my project to .net core 3.0.  I can't open the dashboard.
Will it upgrade to support .net core 3.0 ?

**Comment by heyixiaoran** [comment]
@dumse 
Ths. I try it as your code. It's ok. 
But I want to use project startup.  What should I change IISServerOptions ?

**Comment by fanc-mso** [comment]
Just to add to this, if using Kestrel instead of IIS (for self-hosting in a windows service for example), Kestrel also supports this option:

```
.ConfigureWebHostDefaults(builder =>
                {
                    builder.UseStartup<Startup>();
                    builder.UseKestrel(options =>
                    {
                        options.AllowSynchronousIO = true;
                    });
                })
```

**Comment by heyixiaoran** [comment]
@fanc-mso ths . I like kestrel.
