### ISSUE TITLE
Licence mismatch

### ISSUE THREAD

**Issue by dejx** [guryanovev/CrystalQuartz#92]
Hello

I've noticed that on nuget package (https://www.nuget.org/packages/CrystalQuartz.AspNetCore/6.11.0.3-beta) you are refering to a PERL (GPL) licence, but on the Github project there is a MIT licence used.

Can you please clarify which one is correct?

Br,
Dejan

**Comment by Lexy2** [comment]
Given that the license text was committed later than the build license URL generation code, MIT should be the correct one.
